<?php
namespace Smile\PHPUnitTest\Tests\Demo\Product\CommonProduct;

use Smile\PHPUnitTest\Tests\Base\Product\Product;

class Prodcut extends Product{
    const TYPE = 0;

    public function isCheckType()
    {
        return parent::isCheckType(self::TYPE); // TODO: Change the autogenerated stub
    }
}