<?php
namespace Smile\PHPUnitTest\Tests\Demo\Product\VirtualProduct;

use Smile\PHPUnitTest\Tests\Base\Product\ProductBase;

class Prodcut extends ProductBase{
    const TYPE = 1;
    public function isCheckType()
    {
        return parent::isCheckType(self::TYPE); // TODO: Change the autogenerated stub
    }
}