<?php
namespace Smile\PHPUnitTest\Tests\Base\Product\CommonProduct;

use Smile\PHPUnitTest\Tests\Base\Product\ProductBase;

class Product extends ProductBase{
    const TYPE = 0;

    public function isCheckType()
    {
        return parent::isCheckType(self::TYPE); // TODO: Change the autogenerated stub
    }
}